### ISSUE TITLE
Implement github actions

### ISSUE THREAD

**Issue by jmshapir** [JMSLab/eventstudyr#27]
@santiagohermo now that the package is live I think we're at a good point to reenable Github Actions.

See https://github.com/JMSLab/eventstudyr/pull/12#issuecomment-1362024237 for context.

My guess is the most natural framework for us to use is [`r-lib/actions` v2](https://www.tidyverse.org/blog/2022/06/actions-2-0-0/) but you can let me know if you conclude otherwise.

@nateschor fyi.

**Comment by santiagohermo** [comment]
Thanks @jmshapir! I'll explore github actions and post here when I make some progress.

**Comment by nateschor** [comment]
@santiagohermo you might find some of the utility functions described [here](https://r-pkgs.org/software-development-practices.html#sec-sw-dev-practices-gha) in the R Packages book helpful!

**Comment by santiagohermo** [comment]
Updates @jmshapir @nateschor:
 - In https://github.com/JMSLab/eventstudyr/commit/389f678156ad287a274a008e631d6118c54d58d8 and https://github.com/JMSLab/eventstudyr/commit/36e1c2578e16f86e308acc7faeec19647d6a6934 using the [standard CI workflow](https://github.com/r-lib/actions/tree/v2/examples#standard-ci-workflow)
- In https://github.com/JMSLab/eventstudyr/commit/cb338933fca4932391a326244de8b34ede05b4ee I set up GHA to run on a push to the #27 branch. I did this for testing, but we should delete it before merging.

The new workflow runs appear in [`actions/workflows/check-standard.yaml`](https://github.com/JMSLab/eventstudyr/actions/workflows/check-standard.yaml) instead of [`actions/workflows/R-CMD-check.yaml`](https://github.com/JMSLab/eventstudyr/actions/workflows/R-CMD-check.yaml). (It looks like when I run `usethis` the name of the file changed.

- Should we delete the old workflow?
- It looks like the runs return Errors, for instance for Windows:

![image](https://user-images.githubusercontent.com/45404755/227577929-18c90045-00c0-42c6-8ecb-627daabddfb5.png)


- Error seems to be caused by the warnings we were getting in local runs of `devtools::check()`. I will change code to get rid of those warnings, and see if the checks pass after.

**Comment by santiagohermo** [comment]
New updates @jmshapir @nateschor:

- In https://github.com/JMSLab/eventstudyr/commit/2a9ead98dd2e55a0b11d98e61c6a09a78ee41d96 I made a minor change in code to suppress one warning
- In https://github.com/JMSLab/eventstudyr/commit/a81b5b7b40cbbd2b8d2b2485ea79d436d1df9266 I R-ignored the `/vignettes/` folder to suppress the second warning
  - We can add it back after we figure out how to build the vignette properly

The latest run is [here](https://github.com/JMSLab/eventstudyr/actions/runs/4513131094). As you can see it ran without problems, so I think we are ready to go to PR.

**Comment by nateschor** [comment]
Thanks @santiagohermo! Going to PR sounds good to me.

Figure out the proper way to incorporate the vignette is on my to-do list for #28 :)

**Comment by santiagohermo** [comment]
Continues in #30

**Comment by santiagohermo** [comment]
Summary: In this issue we implemented GitHub Actions. We also prepared [the release of `eventstudyr 1.0.1`](https://github.com/JMSLab/eventstudyr/releases/tag/v1.0.1) in the PR #30.

Changes merged to master in https://github.com/JMSLab/eventstudyr/commit/1ff2c0375d8086a5103f5458bdbbcae6c639e28f.
